# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Marisa\Documents\objectDuplicator/objectDuplicator.ui'
#
# Created: Mon Aug 07 11:38:52 2017
#      by: pyside-uic 0.2.14 running on PySide 1.2.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(867, 801)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.instructionsLabel = QtGui.QLabel(Dialog)
        self.instructionsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.instructionsLabel.setWordWrap(True)
        self.instructionsLabel.setObjectName("instructionsLabel")
        self.verticalLayout_2.addWidget(self.instructionsLabel)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.nameOfSurfaceLabel = QtGui.QLabel(Dialog)
        self.nameOfSurfaceLabel.setObjectName("nameOfSurfaceLabel")
        self.horizontalLayout.addWidget(self.nameOfSurfaceLabel)
        self.nameOfSurfaceLineEdit = QtGui.QLineEdit(Dialog)
        self.nameOfSurfaceLineEdit.setObjectName("nameOfSurfaceLineEdit")
        self.horizontalLayout.addWidget(self.nameOfSurfaceLineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.percentageGeneratedLabel = QtGui.QLabel(Dialog)
        self.percentageGeneratedLabel.setObjectName("percentageGeneratedLabel")
        self.horizontalLayout_2.addWidget(self.percentageGeneratedLabel)
        self.percentageGeneratedLineEdit = QtGui.QLineEdit(Dialog)
        self.percentageGeneratedLineEdit.setObjectName("percentageGeneratedLineEdit")
        self.horizontalLayout_2.addWidget(self.percentageGeneratedLineEdit)
        self.percentageGeneratedHorizontalSlider = QtGui.QSlider(Dialog)
        self.percentageGeneratedHorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.percentageGeneratedHorizontalSlider.setObjectName("percentageGeneratedHorizontalSlider")
        self.horizontalLayout_2.addWidget(self.percentageGeneratedHorizontalSlider)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.scaleLabel = QtGui.QLabel(Dialog)
        self.scaleLabel.setObjectName("scaleLabel")
        self.horizontalLayout_4.addWidget(self.scaleLabel)
        self.scaleLineEdit = QtGui.QLineEdit(Dialog)
        self.scaleLineEdit.setObjectName("scaleLineEdit")
        self.horizontalLayout_4.addWidget(self.scaleLineEdit)
        self.scaleHorizontalSlider = QtGui.QSlider(Dialog)
        self.scaleHorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.scaleHorizontalSlider.setObjectName("scaleHorizontalSlider")
        self.horizontalLayout_4.addWidget(self.scaleHorizontalSlider)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.randomizeScaleCheckBox = QtGui.QCheckBox(Dialog)
        self.randomizeScaleCheckBox.setObjectName("randomizeScaleCheckBox")
        self.horizontalLayout_5.addWidget(self.randomizeScaleCheckBox)
        self.turnOffRandomizedRotationCheckBox = QtGui.QCheckBox(Dialog)
        self.turnOffRandomizedRotationCheckBox.setObjectName("turnOffRandomizedRotationCheckBox")
        self.horizontalLayout_5.addWidget(self.turnOffRandomizedRotationCheckBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.minRandomizedScaleValueLabel = QtGui.QLabel(Dialog)
        self.minRandomizedScaleValueLabel.setObjectName("minRandomizedScaleValueLabel")
        self.horizontalLayout_3.addWidget(self.minRandomizedScaleValueLabel)
        self.minRandomizedScaleLineEdit = QtGui.QLineEdit(Dialog)
        self.minRandomizedScaleLineEdit.setObjectName("minRandomizedScaleLineEdit")
        self.horizontalLayout_3.addWidget(self.minRandomizedScaleLineEdit)
        self.minRandomizedScaleValueHorizontalSlider = QtGui.QSlider(Dialog)
        self.minRandomizedScaleValueHorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.minRandomizedScaleValueHorizontalSlider.setObjectName("minRandomizedScaleValueHorizontalSlider")
        self.horizontalLayout_3.addWidget(self.minRandomizedScaleValueHorizontalSlider)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.maxRandomizedScaleValueLabel = QtGui.QLabel(Dialog)
        self.maxRandomizedScaleValueLabel.setObjectName("maxRandomizedScaleValueLabel")
        self.horizontalLayout_6.addWidget(self.maxRandomizedScaleValueLabel)
        self.maxRandomizedScaleLineEdit = QtGui.QLineEdit(Dialog)
        self.maxRandomizedScaleLineEdit.setObjectName("maxRandomizedScaleLineEdit")
        self.horizontalLayout_6.addWidget(self.maxRandomizedScaleLineEdit)
        self.maxRandomizedScaleValueHorizontalSlider = QtGui.QSlider(Dialog)
        self.maxRandomizedScaleValueHorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.maxRandomizedScaleValueHorizontalSlider.setObjectName("maxRandomizedScaleValueHorizontalSlider")
        self.horizontalLayout_6.addWidget(self.maxRandomizedScaleValueHorizontalSlider)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.verticalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.createGeometryPushButton = QtGui.QPushButton(Dialog)
        self.createGeometryPushButton.setObjectName("createGeometryPushButton")
        self.verticalLayout.addWidget(self.createGeometryPushButton)
        self.deleteLocatorsPushButton = QtGui.QPushButton(Dialog)
        self.deleteLocatorsPushButton.setObjectName("deleteLocatorsPushButton")
        self.verticalLayout.addWidget(self.deleteLocatorsPushButton)
        self.emptyScenePushButton = QtGui.QPushButton(Dialog)
        self.emptyScenePushButton.setObjectName("emptyScenePushButton")
        self.verticalLayout.addWidget(self.emptyScenePushButton)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.itemsCreatedLabel = QtGui.QLabel(Dialog)
        self.itemsCreatedLabel.setObjectName("itemsCreatedLabel")
        self.verticalLayout_3.addWidget(self.itemsCreatedLabel)
        self.itemsCreatedListWidget = QtGui.QListWidget(Dialog)
        self.itemsCreatedListWidget.setObjectName("itemsCreatedListWidget")
        self.verticalLayout_3.addWidget(self.itemsCreatedListWidget)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.instructionsLabel.setText(QtGui.QApplication.translate("Dialog", "To use tool, enter name of surface you want objects duplicated on below and then select objects to duplicated. Press button to create geometry.", None, QtGui.QApplication.UnicodeUTF8))
        self.nameOfSurfaceLabel.setText(QtGui.QApplication.translate("Dialog", "Name of Surface: ", None, QtGui.QApplication.UnicodeUTF8))
        self.percentageGeneratedLabel.setText(QtGui.QApplication.translate("Dialog", "Percentage Generated (must be between 1 and 10): ", None, QtGui.QApplication.UnicodeUTF8))
        self.scaleLabel.setText(QtGui.QApplication.translate("Dialog", "Scale (must be between 1 and 10):", None, QtGui.QApplication.UnicodeUTF8))
        self.randomizeScaleCheckBox.setText(QtGui.QApplication.translate("Dialog", "Randomize Scale", None, QtGui.QApplication.UnicodeUTF8))
        self.turnOffRandomizedRotationCheckBox.setText(QtGui.QApplication.translate("Dialog", "Turn Off Randomized Rotation", None, QtGui.QApplication.UnicodeUTF8))
        self.minRandomizedScaleValueLabel.setText(QtGui.QApplication.translate("Dialog", "Minimum Scale:", None, QtGui.QApplication.UnicodeUTF8))
        self.maxRandomizedScaleValueLabel.setText(QtGui.QApplication.translate("Dialog", "Maximum Scale:", None, QtGui.QApplication.UnicodeUTF8))
        self.createGeometryPushButton.setText(QtGui.QApplication.translate("Dialog", "Create Locators and Geometry", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteLocatorsPushButton.setText(QtGui.QApplication.translate("Dialog", "Delete Locators", None, QtGui.QApplication.UnicodeUTF8))
        self.emptyScenePushButton.setText(QtGui.QApplication.translate("Dialog", "Empty Scene", None, QtGui.QApplication.UnicodeUTF8))
        self.itemsCreatedLabel.setText(QtGui.QApplication.translate("Dialog", "Items Created:", None, QtGui.QApplication.UnicodeUTF8))

